# NumPy Fundamentals

### 1. Introduction: What is NumPy and Why Use It?

At our previous class, we saw a problem: performing mathematical operations on large lists of numbers in Python is slow and requires writing `for` loops. NumPy (Numerical Python) is the solution.

**NumPy** is the fundamental package for scientific computing in Python. It provides a powerful object called an **N-dimensional array (`ndarray`)** and a huge collection of functions for working with these arrays.

**Why is it so essential?**
1.  **Speed:** NumPy operations are implemented in C, making them much faster than standard Python loops.
2.  **Convenience:** It allows you to perform mathematical operations on entire arrays at once (a concept called **vectorization**), which means less code and fewer bugs.
3.  **Foundation of the Ecosystem:** Libraries like Pandas, Matplotlib, and Scikit-learn are all built on top of NumPy.

By convention, we almost always import NumPy with the alias `np`.

In [1]:
import numpy as np

### 2. Creating NumPy Arrays

The core of NumPy is the `ndarray`. You can create one in several ways.

In [3]:
# 1. From a Python list
data = [1,2,3,4,5]
print(data,type(data))

[1, 2, 3, 4, 5] <class 'list'>


In [14]:
new_data=[1,2,3,4,5,6,7]
print(new_data)
print(type(new_data))
new=np.array(new_data)
print(new.dtype)
print(new.size)
print(new.shape)
print(new.ndim)

[1, 2, 3, 4, 5, 6, 7]
<class 'list'>
int64
7
(7,)
1


In [12]:
my_array=np.array(data)
#my_array
print(my_array)
print("type ", type(my_array))
print("data type ", my_array.dtype) #element of array
print("Dimension ",my_array.ndim)
print("shape ", my_array.shape)
print("size ",my_array.size)#total number of element

[1 2 3 4 5]
type  <class 'numpy.ndarray'>
data type  int64
Dimension  1
shape  (5,)
size  5


In [13]:
#2D array
two_dim=[[1,2,3],[4,5,6]]
print(two_dim,type(two_dim))

[[1, 2, 3], [4, 5, 6]] <class 'list'>


In [18]:
twomy_array=np.array(two_dim)
print(twomy_array)
print("type ",twomy_array)
print("data type ", twomy_array.dtype)
print("dimension ", twomy_array.ndim)
print("Shape ",twomy_array.shape)
print("size ",twomy_array.size)

[[1 2 3]
 [4 5 6]]
type  [[1 2 3]
 [4 5 6]]
data type  int64
dimension  2
Shape  (2, 3)
size  6


In [21]:
#3D array
three_data=[[[1,2],[4,5]],[[6,7],[8,9]],[[10,11],[12,13]]]
print(three_data)

[[[1, 2], [4, 5]], [[6, 7], [8, 9]], [[10, 11], [12, 13]]]


In [22]:
three_array=np.array(three_data)
print(three_array)
print("type ",three_array)
print("data type ", three_array.dtype)
print("dimension ", three_array.ndim)
print("Shape ",three_array.shape)
print("size ",three_array.size)

[[[ 1  2]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]]]
type  [[[ 1  2]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]]

 [[10 11]
  [12 13]]]
data type  int64
dimension  3
Shape  (3, 2, 2)
size  12


In [19]:
#self practise
#1D array
"""new=[1,2,3,4,5,6,7,8]
print(new)
new_array=np.array(new)
print(new_array)
print("type :",new_array)
print("datatype :",new_array.dtype)
print("dimension :",new_array.ndim)
print("Shape :",new_array.shape)
print("Size :",new_array.size)

#2D array
new=[[1,2,3,4],[5,6,7,8]]
print(new)
new_array=np.array(new)
print(new_array)
print("type :",new_array)
print("datatype :",new_array.dtype)
print("dimension :",new_array.ndim)
print("Shape :",new_array.shape)
print("Size :",new_array.size)

#3D array
new=[[[1,2],[3,4]],[[5,6],[7,8]]]
print(new)
new_array=np.array(new)
print(new_array)
print("type :",new_array)
print("datatype :",new_array.dtype)
print("dimension :",new_array.ndim)
print("Shape :",new_array.shape)
print("Size :",new_array.size)

#4D array
new=[[[[1],[2]],[[3],[4]]],[[[5],[6]],[[7],[8]]]]
print(new)
new_array=np.array(new)
print(new_array)
print("type :",new_array)
print("datatype :",new_array.dtype)
print("dimension :",new_array.ndim)
print("Shape :",new_array.shape)
print("Size :",new_array.size)"""

#5D array
new=[[[[[1],[1]],[[2],[2]]],[[[3],[3]],[[4],[4]]]],[[[[5],[5]],[[6],[6]]],[[[7],[7]],[[8],[8]]]]]
print(new)
new_array=np.array(new)
print(new_array)
print("type :",new_array)
print("datatype :",new_array.dtype)
print("dimension :",new_array.ndim)
print("Shape :",new_array.shape)
print("Size :",new_array.size)

[[[[[1], [1]], [[2], [2]]], [[[3], [3]], [[4], [4]]]], [[[[5], [5]], [[6], [6]]], [[[7], [7]], [[8], [8]]]]]
[[[[[1]
    [1]]

   [[2]
    [2]]]


  [[[3]
    [3]]

   [[4]
    [4]]]]



 [[[[5]
    [5]]

   [[6]
    [6]]]


  [[[7]
    [7]]

   [[8]
    [8]]]]]
type : [[[[[1]
    [1]]

   [[2]
    [2]]]


  [[[3]
    [3]]

   [[4]
    [4]]]]



 [[[[5]
    [5]]

   [[6]
    [6]]]


  [[[7]
    [7]]

   [[8]
    [8]]]]]
datatype : int64
dimension : 5
Shape : (2, 2, 2, 2, 1)
Size : 16


In [23]:
# 2. Using built-in functions
# np.arange is like Python's range() but returns a NumPy array
array_range = np.arange(0,100,10)
print(array_range)
print(array_range.ndim)

[ 0 10 20 30 40 50 60 70 80 90]
1


In [19]:
#using range
new_arange=np.arange(0,100,2.5)
print(new_arange)

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5 25.  27.5 30.  32.5
 35.  37.5 40.  42.5 45.  47.5 50.  52.5 55.  57.5 60.  62.5 65.  67.5
 70.  72.5 75.  77.5 80.  82.5 85.  87.5 90.  92.5 95.  97.5]


In [22]:
new_range=np.arange(0,500,49)
print(new_range)

[  0  49  98 147 196 245 294 343 392 441 490]


In [25]:
# Create an array of all zeros
zero_array=np.zeros((2,3))
print(zero_array)
print(zero_array.dtype)

[[0. 0. 0.]
 [0. 0. 0.]]
float64


In [27]:
new_zero=np.zeros((7,4),dtype="int")
print(new_zero)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


In [27]:
# Create an array of all ones
one_array=np.ones((2,3),dtype="int")
print(one_array)
print(one_array.dtype)

[[1 1 1]
 [1 1 1]]
int64


In [30]:
new_one=np.ones((3,4),dtype="int")
print(new_one)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [30]:
# Create an array with a specific number of points between a start and end value
linespace_array=np.linspace(0,99,10)
linespace_array

array([ 0., 11., 22., 33., 44., 55., 66., 77., 88., 99.])

In [22]:
new_linespace=np.linspace(0,100,5)
print(new_linespace)

[  0.  25.  50.  75. 100.]


In [32]:
np.linspace(1,100,5)

array([  1.  ,  25.75,  50.5 ,  75.25, 100.  ])

In [39]:
new_linespace=np.linspace(0,500,50)
print(new_linespace)

[  0.          10.20408163  20.40816327  30.6122449   40.81632653
  51.02040816  61.2244898   71.42857143  81.63265306  91.83673469
 102.04081633 112.24489796 122.44897959 132.65306122 142.85714286
 153.06122449 163.26530612 173.46938776 183.67346939 193.87755102
 204.08163265 214.28571429 224.48979592 234.69387755 244.89795918
 255.10204082 265.30612245 275.51020408 285.71428571 295.91836735
 306.12244898 316.32653061 326.53061224 336.73469388 346.93877551
 357.14285714 367.34693878 377.55102041 387.75510204 397.95918367
 408.16326531 418.36734694 428.57142857 438.7755102  448.97959184
 459.18367347 469.3877551  479.59183673 489.79591837 500.        ]


In [33]:
#identity matrix: square matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [39]:
eye_array = np.eye(5,6,2)
eye_array

array([[0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0.]])

In [40]:
#change data type of element
eye_array.astype("int64")

array([[0, 0, 1, 0, 0, 0],
       [0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 1],
       [0, 0, 0, 0, 0, 0]])

### 3. The Power of Vectorization

This is NumPy's killer feature. You can perform operations on entire arrays without writing explicit loops. This is called **vectorization**.

In [23]:
# The Old Way (Python lists)
list_a=[1,2,3]
list_b=[4,5,6]
list_c=[]
for i in range(len(list_a)):
    list_c.append(list_a[i]+list_b[i])
print(list_c)


[5, 7, 9]


In [42]:
# The NumPy Way (Vectorized)
array_a=np.array([1,2,3])
array_b=np.array([4,5,6])
print(array_a,array_b)
array_c=array_a + array_b
print(array_c)

[1 2 3] [4 5 6]
[5 7 9]


In [30]:
new_a=np.array([1,2,3])
new_b=np.array([3,4,5])
print(new_a)
print(new_b)
new_c=new_a+new_b
print(new_c)

print(new_c.shape)
print(type(new_c))
print(new_c.size)
print(new_c.ndim)
new_c **3

[1 2 3]
[3 4 5]
[4 6 8]
(3,)
<class 'numpy.ndarray'>
3
1


array([ 64, 216, 512])

In [43]:
# This works for all standard math operations
array_c **2

array([25, 49, 81])

In [44]:
#list of obtained marks
obt_marks=np.array([34,37,40,55,90])
#list of full marks
full_marks=np.array([50,50,100,100,100])
sum=0
#calculate percentage of student score
(obt_marks/full_marks)*100

array([68., 74., 40., 55., 90.])

In [42]:
new_one=np.array([1,2,3,4])
print(new_one)
new_two=np.array([5,6,7,8])
print(new_two)
new_result=[]
new_result=new_one-new_two
print(new_result)

[1 2 3 4]
[5 6 7 8]
[-4 -4 -4 -4]


### 4. Array Attributes and Reshaping

You can easily inspect the properties of an array and change its shape.

In [45]:
arr=np.arange(12)
print(f"original: {arr}")

original: [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [53]:
# Key Attributes
# The dimensions of the array

# The total number of elements

# The number of axes (dimensions)

# The data type of the elements

print(arr.size)
# Reshaping
# .reshape() returns a new array with the same data but a new shape.
# The new shape must be compatible with the original size (e.g., 12 = 3 * 4)
arr.reshape(3,2,2)
arr.reshape(3,2,2).ndim
arr.reshape(1,2,3,2)

12


array([[[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]]]])

In [43]:
new_reshape=np.arange(50)
print(new_reshape)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


In [37]:
reshape_a=np.arange(0,100,5)
print(reshape_a)

new_re=reshape_a.reshape(4,5)
print(new_re)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]
[[ 0  5 10 15 20]
 [25 30 35 40 45]
 [50 55 60 65 70]
 [75 80 85 90 95]]


In [44]:
new_reshape.shape

(50,)

In [48]:
new=new_reshape.reshape(2,5,5)
print(new)

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]]

 [[25 26 27 28 29]
  [30 31 32 33 34]
  [35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]]]


### 5. Indexing, Slicing, and Broadcasting

Accessing elements in NumPy arrays is similar to Python lists but more powerful.

In [55]:
data_list=[[1,2,3],[4,5,6]]
data_list[1][1]


5

In [61]:
new_data=[[[[ 0,  1],
         [ 2,  3],
         [ 4,  5]],

        [[ 6,  7],
         [ 8,  9],
         [10, 11]]]]
new_data[0][0][2][1]

5

In [54]:
data = np.arange(20).reshape(4, 5) # 4 rows, 5 columns
print("Our 2D array:\n", data)#ctrl,shift,- for split the shell

Our 2D array:
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [60]:
# --- Indexing ---
# Get a single element [row, column]
data[0][2]
print(data[0,2])

2


In [61]:
# --- Slicing ---
# Get the first two rows
data[0:2]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [62]:
# Get columns 1 and 2
data[:,1:3]

array([[ 1,  2],
       [ 6,  7],
       [11, 12],
       [16, 17]])

In [64]:
data[1:3,2:4]

array([[ 7,  8],
       [12, 13]])

In [70]:
data[2:4,3:5]

array([[13, 14],
       [18, 19]])

In [63]:
three_data=[[[1,2],[4,5]],[[6,7],[8,9]],[[10,11],[12,13]]]
three_data[1][0][0]
print(three_data)

[[[1, 2], [4, 5]], [[6, 7], [8, 9]], [[10, 11], [12, 13]]]


In [71]:
# --- Broadcasting ---
# Broadcasting describes how NumPy treats arrays with different shapes during arithmetic operations.
# It 'stretches' the smaller array to match the shape of the larger one.

# Add 100 to every element in the array
data +100

array([[100, 101, 102, 103, 104],
       [105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114],
       [115, 116, 117, 118, 119]])

In [78]:
array_1=np.array([[1,2],[3,4]])
print(array_1,array_1.shape)
array_2=np.array([[1],[4]])
print(array_2,array_2.shape)
array_1 + array_2

[[1 2]
 [3 4]] (2, 2)
[[1]
 [4]] (2, 1)


array([[2, 3],
       [7, 8]])

In [84]:
data=np.array([[1,2,3],[4,5,6]])
data.resize((2,2),refcheck=False)
data

array([[1, 2],
       [3, 4]])

In [86]:
data.resize((3,3),refcheck=False)
data

array([[1, 2, 3],
       [4, 0, 0],
       [0, 0, 0]])

### 6. Essential Statistical Functions

NumPy is packed with useful functions for performing statistical analysis.

The `axis` parameter is crucial here:
*   `axis=0`: Perform the operation **down the columns** (collapsing the rows).
*   `axis=1`: Perform the operation **across the rows** (collapsing the columns).

In [38]:
scores = np.array([
    [85, 92, 88], # Student 1 scores
    [76, 81, 79], # Student 2 scores
    [95, 91, 93] ]) # Student 3 scores


print(f"Scores array:\n{scores}\n")

Scores array:
[[85 92 88]
 [76 81 79]
 [95 91 93]]



In [39]:
# --- Operations on the entire array ---
print("sum :" ,scores.sum())
print("mean :", scores.mean())
print("Std : ",scores.std())
print("min : ", scores.min())
print("max :",scores.max())

sum : 780
mean : 86.66666666666667
Std :  6.377042156569663
min :  76
max : 95


In [41]:
# --- Operations along an axis ---
# Get the average score for each ASSIGNMENT (column-wise)
scores.mean(axis=0)

array([85.33333333, 88.        , 86.66666667])

In [10]:
# Get the average score for each STUDENT (row-wise)
scores.mean(axis=1)

array([88.33333333, 78.66666667, 93.        ])

In [12]:
scores.min(axis=0)

array([76, 81, 79])

In [7]:
data=[[100, 101, 102, 103, 104],
       [105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114],
       [115, 116, 117, 118, 119]]
data
data=np.array(data)
data

array([[100, 101, 102, 103, 104],
       [105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114],
       [115, 116, 117, 118, 119]])

In [12]:
print("sum :",data.sum())
print("mean :", data.mean())
print("Std :",data.std())
print("min :",data.min())
print("max :",data.max())

sum : 2190
mean : 109.5
Std : 5.766281297335398
min : 100
max : 119


In [13]:
data.mean(axis=0)

array([107.5, 108.5, 109.5, 110.5, 111.5])

In [14]:
data.mean(axis=1)

array([102., 107., 112., 117.])

In [15]:
data.min(axis=0)

array([100, 101, 102, 103, 104])

In [16]:
data.max(axis=0)

array([115, 116, 117, 118, 119])

### 7. Boolean Indexing (Filtering)

This is one of NumPy's most powerful features. You can use a boolean array to select elements from another array. This is the foundation of filtering in Pandas.

In [42]:
scores_1d = np.array([77, 95, 81, 68, 92, 88, 79, 99, 65, 85])
print(f"All scores: {scores_1d}")

All scores: [77 95 81 68 92 88 79 99 65 85]


In [49]:
new_score=np.array([34,46,29,43,37,23,17])
#print(new_score)
print(f"all score: {new_score}")
a=new_score>40
new_score[a]


all score: [34 46 29 43 37 23 17]


array([46, 43])

In [15]:
# Step 1: Create a boolean mask
# This creates a new array of True/False values
boolean_mask=scores_1d>90
boolean_mask

array([False,  True, False, False,  True, False, False,  True, False,
       False])

In [16]:
# Step 2: Use the mask to filter the original array
# This selects only the elements where the mask is True
scores_1d[boolean_mask]

array([95, 92, 99])

In [17]:
# You can also combine conditions using & (and) and | (or)
# Note: you MUST use parentheses around each condition
scores_1d[(scores_1d>80)&(scores_1d<90)]

array([81, 88, 85])

In [19]:
scores_1d[scores_1d<70]=70

In [21]:
scores_1d

array([77, 95, 81, 70, 92, 88, 79, 99, 70, 85])

In [48]:
arr=np.random.randint(1,100,20).reshape(4,5)
arr


array([[87, 68, 31, 20, 27],
       [41, 15, 41, 14, 97],
       [40,  4, 39, 70, 45],
       [ 3, 37, 71, 56, 45]], dtype=int32)

In [49]:
new1=arr[arr>90]
new1

array([97], dtype=int32)

In [52]:
new2=arr[arr<20]
new2[new2<20]=0
new2

array([0, 0, 0, 0], dtype=int32)

In [51]:
new3=arr[(arr>40)&(arr<=60)]
new3

array([41, 41, 45, 56, 45], dtype=int32)

In [17]:
data=[[100, 101, 102, 103, 104],
       [105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114],
       [115, 116, 117, 118, 119]]
data=np.array(data)
data

array([[100, 101, 102, 103, 104],
       [105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114],
       [115, 116, 117, 118, 119]])

In [18]:
new=data[(data>105)&(data<119)]
new

array([106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118])

In [20]:
even=data[(data%2)==0]
even

array([100, 102, 104, 106, 108, 110, 112, 114, 116, 118])

# 8. Fancy Indexing
**Fancy indexing** is a term for using an *array of indices* to access multiple array elements at once. While slicing lets you select *contiguous blocks* of elements, fancy indexing lets you select **any combination** of elements, in any order. This is incredibly powerful.

In [58]:
# --- 1D Fancy Indexing ---
list_1d=np.random.randint(10,20,10)
list_1d

array([10, 13, 15, 11, 10, 17, 10, 19, 11, 14], dtype=int32)

In [59]:
list_1d[3]
print(list_1d[1:5])

[13 15 11 10]


In [60]:
# Create an array of indices to select
ind_value=np.array([2,3,7,8,0])
ind_value

array([2, 3, 7, 8, 0])

In [61]:
# Use the indices to 'pick' elements from the original array
list_1d[ind_value]


array([15, 11, 19, 11, 10], dtype=int32)

In [63]:
# --- 2D Fancy Indexing ---
arr_2d=np.arange(12).reshape(4,3)
arr_2d

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [64]:
# Select specific rows in a desired order
arr_2d[[3,2,0]]

array([[ 9, 10, 11],
       [ 6,  7,  8],
       [ 0,  1,  2]])

In [72]:
# Select specific elements using (row, column) coordinates

row_indices=np.array([0,2,3])
col_indices=np.array([1,2,0])

In [73]:
# This will select elements at (0,1), (2,2), and (3,0)
arr_2d[row_indices,col_indices]

array([1, 8, 9])

In [21]:
data=[[100, 101, 102, 103, 104],
       [105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114],
       [115, 116, 117, 118, 119]]
data=np.array(data)
data

array([[100, 101, 102, 103, 104],
       [105, 106, 107, 108, 109],
       [110, 111, 112, 113, 114],
       [115, 116, 117, 118, 119]])

In [22]:
data[(1,2,3),(0,2,3)]

array([105, 112, 118])

---

### Hands-On Lab: Matrix Calculations and Score Filtering

**Scenario:** You have the scores of 5 students on 4 different assignments. Your task is to perform several analyses using NumPy.

In [81]:
# Here is the starting data
student_scores = np.array([
    [85, 90, 88, 92],  # Student 1
    [78, 81, 84, 80],  # Student 2
    [92, 95, 91, 97],  # Student 3
    [65, 70, 68, 72],  # Student 4
    [88, 85, 89, 94]   # Student 5
])

In [82]:
# Task 1: Calculate the average score for each student (row-wise average).
student_scores.mean(axis=1)

array([88.75, 80.75, 93.75, 68.75, 89.  ])

In [83]:
# Task 2: Calculate the average score for each assignment (column-wise average).
student_scores.mean(axis=0)

array([81.6, 84.2, 84. , 87. ])

In [92]:
# Task 3: The professor decides to curve all scores by adding 3 points. Create a new array `curved_scores`.
curved_scores = student_scores+3
print(curved_scores)

[[ 88  93  91  95]
 [ 81  84  87  83]
 [ 95  98  94 100]
 [ 68  73  71  75]
 [ 91  88  92  97]]


In [93]:
# Task 4: Find all the original scores that were 90 or above.
student_scores[student_scores>90]

array([92, 92, 95, 91, 97, 94])

### Assignment: Analyze Numeric Data and Filter Top 10% Scores

**Your Task:**
You are given a larger dataset of 100 final exam scores. Your goal is to perform a statistical analysis and identify the students who are in the top 10%.

1.  **Create the NumPy array** provided below.
2.  **Calculate and print** the following statistics for the entire dataset:
    *   Mean score
    *   Median score (Hint: `np.median()`)
    *   Standard Deviation
    *   Minimum and Maximum scores
3.  **Determine the threshold** for the top 10% of scores. A score needs to be greater than the 90th percentile to be in the top 10%. (Hint: Use `np.percentile(array, 90)`).
4.  **Use boolean indexing** to create a new array called `top_performers` that contains only the scores which are in the top 10%.
5.  **Print** the `top_performers` array and the total number of students in this group.

In [53]:
# 1. Starting data: 100 final exam scores
np.random.seed(10)
final_exam_scores = np.random.normal(loc=78, scale=12, size=100).clip(0, 100).round(1)
print(f"--- Original Dataset (first 10 scores) ---\n{final_exam_scores[:10]}\n")

--- Original Dataset (first 10 scores) ---
[94.  86.6 59.5 77.9 85.5 69.4 81.2 79.3 78.1 75.9]



In [61]:
# 2. Calculate statistics
# YOUR CODE HERE
new=np.array([94.,  86.6, 59.5, 89.6, 85.5, 44.4, 81.2, 79.3,38.1 ,95.9])
print("sum :",new.sum())
print("mean:",new.mean())
print("std :",new.std())
print("median: ",np.median(new))
print("min :",new.min())
print("max :",new.max())

sum : 754.0999999999999
mean: 75.41
std : 19.61950305181046
median:  83.35
min : 38.1
max : 95.9


In [62]:
# 3. Determine the top 10% threshold (90th percentile)
# YOUR CODE HERE
top=np.percentile(new, 90)
top

np.float64(94.19)

In [63]:
# 4. Filter to get the top performing scores
# YOUR CODE HERE
filter=new[(new>=top)]
filter

array([95.9])

In [ ]:
# 5. Print the results
# YOUR CODE HERE
